Module5 task1
htmlacademy-react/120631-six-cities-7 pull request #8
Opened 2021-07-08 07:12 UTC by kalininmax

2021-07-08 07:15 UTC, kalininmax commented on project/src/store/action.js
> +    payload: '',
Не знаю, что записать в payload.
Какой-то city переданный в параметрах функции changeCity?

2021-07-08 07:18 UTC, kalininmax commented on project/src/const.js
> +  CITY_ID: '/city/:city',
Сначала сделал путь **/:city**
Но тогда в параметр **city** стали попадать **favorites** и остальное что после **/** идёт, поэтому сделал так. Может как-то по другому можно?

2021-07-08 07:22 UTC, kalininmax commented on project/src/components/app/app.jsx
> +          <Home cities={Object.values(City)} offers={offers} />
У меня City — объект-перечисление, а внутри Home список городов нужен в виде массива.
Нормально так преобразовывать или как-то иначе сделать?

2021-07-08 07:25 UTC, kalininmax commented on project/src/components/app/app.jsx
> +          render={(props) => <Home props={props} cities={Object.values(City)} offers={offers} />}
До этого момента не использовал с рендер-пропс. А тут понадобились служебные пропсы внутри компонента. Я правильно это реализовал?

2021-07-08 07:28 UTC, kalininmax commented on project/src/components/pages/home/home.jsx
> +  const selectedCity = props ? props.match.params.city : City.PARIS;
Здесь получаю выбранный город из адресной строки, а когда его нет ставлю Париж.
Почему-то линтер ругается на валидацию этих пропсов (props.match.params.city), хотя внизу прописал для них PropTypes.

2021-07-08 10:21 UTC, balesniy requested changes
- с redux все хорошо, нужно поправить первоначальную загрузку списка предложений - отдельным действием, редьюсер его уже ждет, но нужно сделать dispatch
- нужно научить компонент получать текущий город из redux и отправлять событие смены города, для этого его подключаем с помощью connect
- в ПР нет компонента Favorites, но его уже нужно доработать - сгруппировать список предложений по городам
- в компоненте отдельного предложения Offer функциональность активной карточки не предусмотрена ТЗ
- типичная проблема - использование случайных ключей в списках - `key={nanoid()}` - ключи должны быть не только уникальными, но и стабильными, см https://ru.reactjs.org/docs/glossary.html#keys
- useEffect карты добавляет новые маркеры при каждой смене параметров, но не удаляет их, нужно добавить колбэк "очистки эффекта", см демку про установку-снятие обработчика
- отзывы в списке нужно отсортировать от новых к старым (новые сверху)

2021-07-09 10:06 UTC, balesniy approved these changes
:+1:

2021-07-09 10:06 UTC, balesniy commented on project/src/components/pages/offer/offer.jsx
> +              {otherPlaces.map((card) => <OfferCard key={card.id} card={card} onHover={handleCardHover} />)}
на этом экране нам onHover не нужен

2021-07-09 10:06 UTC, balesniy commented on project/src/components/ui/map/map.jsx
> +    // return markers.clearLayers();
из эффекта нужно вернуть функцию-колбэк

2021-07-09 10:07 UTC, merged